import { useState } from 'react'
import { Configuration, OpenAIApi } from "openai";

import Topbar from '../topbar/Topbar';

import "./generateImage.css"
import Button from '@mui/material/Button';
import Grid from '@mui/material/Grid';
import Container from '@mui/material/Container';
import { Typography, TextField } from '@mui/material';
import ImageList from '@mui/material/ImageList';

const GenerateImage = () => {
  const [propmt, setPromt] = useState("");
  const [imageURL, setImageURL] = useState("");

  const configuration = new Configuration({
    organization: "org-GOgOqEbg9oJpjeM0MTMM0Vgv",
    apiKey: import.meta.env.VITE_Open_AI_Key,
  });

  const openai = new OpenAIApi(configuration);
  const generateImage = async () => {
    setImageURL("");
    const res = await openai.createImage({
      prompt: propmt,
      n: 1,
      size: "1024x1024",
    });
    
    setImageURL(res.data.data[0].url);
    

  }

  return (
    <>
    <Topbar />

    <Container maxWidth="" 
                sx={{
                    width:"720px",
                }} 
            >
                <Grid   container
                        direction="row"
                        justifyContent="space-around"
                        alignItems="center"
                        sx={{marginTop:"200px"}}
                        >
                        <Typography variant="h3" sx={{color:"#e582e5"}}>Image Generated by AI</Typography>
                       
                            
                </Grid>
                
                <Grid   container
                        direction="row"
                        justifyContent="space-around"
                        alignItems="center"
                        spacing={0}
                        sx={{
                            width:"auto",
                            marginTop:"50px"
                        }} 
                >
                    
                    < TextField
                      required
                      label="Required"
                      variant="outlined"
                        
                      sx={{
                          width:"500px",
                          marginBottom:"50px"
                      }} 
                      onChange={(e) => (setPromt(e.target.value))}
                      placeholder="Type in here…"
                        
                      />
                      
                      <Grid container
                        direction="row"
                        justifyContent="space-around"
                        alignItems="center"
                        spacing={0}
                      >
                        <Button onClick={generateImage} >Generate an Image</Button>
                        {imageURL.length > 0 ? 
                                              <img src={imageURL}  sx={{width:"100%", height:"auto", marginTop:"25px", marginBottom:"25px"}} /> 
                                            : 
                                            <>
                                            </>
                        } 
                      </Grid>
                      
                      
                      
                </Grid>
            </Container>
    </>
      
  )
}

export default GenerateImage
